from . import ir_model
from . import studio_change
from . import studio_app
from . import studio_automation
from . import studio_server_action
from . import studio_report_builder
from . import studio_dashboard
from . import studio_model_constraint
from . import studio_custom_code
from . import res_config_settings
